name: DL

on: workflow_dispatch

jobs:
  job_1:
    name: dl-art
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        github-token: ${{ secrets.GH_PAT }} # token with actions:read permissions on target repo
        repository: Defiect/cpython
        run-id: 16395215160
        path: path/to/artifacts
    - name: Display structure of downloaded files
      run: ls -R path/to/artifacts
    
    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{ steps.version.outputs.version }}
        tag_name: asedf
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
    
    - name: upload windows artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./bin/azblogfilter.windows-amd64.zip
        asset_name: azblogfilter.windows-amd64.zip
        asset_content_type: application/zip
